# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 15:42
from __future__ import unicode_literals

import coding.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random', models.IntegerField()),
                ('attempt', models.IntegerField()),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('uploadtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('qnset', models.FileField(upload_to=coding.models.qn_upload)),
                ('solution', models.FileField(upload_to=coding.models.sol_upload)),
                ('ans', models.FileField(null=True, upload_to=coding.models.ans_upload)),
                ('codefile', models.FileField(null=True, upload_to=coding.models.code_upload)),
                ('qtype', models.CharField(choices=[('small', 'small'), ('large', 'large')], default='small', max_length=10)),
                ('result', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('unattempted', 'unattempted')], default='unattempted', max_length=12)),
                ('coderesult', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail')], default='fail', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Qns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('smalllimits', models.TextField()),
                ('largelimits', models.TextField()),
                ('inputexample', models.TextField()),
                ('outputexample', models.TextField()),
                ('utimesmall', models.IntegerField()),
                ('utimelarge', models.IntegerField()),
                ('smallscript', models.FileField(null=True, upload_to=coding.models.smallscript_upload)),
                ('largescript', models.FileField(null=True, upload_to=coding.models.largescript_upload)),
            ],
        ),
        migrations.AddField(
            model_name='ans',
            name='qn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.Qns'),
        ),
        migrations.AddField(
            model_name='ans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
