# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='random',
        ),
        migrations.AlterField(
            model_name='answer',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
