# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='solnum',
            field=models.IntegerField(default=0),
        ),
    ]
