# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qns',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
