# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20160714_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
