# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_answer_solnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='result',
            field=models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('unattempted', 'unattempted'), ('in-progress', 'in-progress')], default='unattempted', max_length=12),
        ),
    ]
