# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_testattempt_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='attempt',
        ),
        migrations.AddField(
            model_name='answer',
            name='large_attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='small_attempt',
            field=models.IntegerField(default=1),
        ),
    ]
