# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_auto_20160802_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('cause', models.CharField(max_length=50)),
                ('starttime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
