# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_auto_20160714_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
