# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_userlockdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
