# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='NCH', max_length=50),
            preserve_default=False,
        ),
    ]
