# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansint', models.IntegerField(null=True)),
                ('anschar', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreQn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='scorecardlink',
            name='qn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ScoreQn'),
        ),
        migrations.AddField(
            model_name='scorecardlink',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ScoreCard'),
        ),
        migrations.AddField(
            model_name='scoreans',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ScoreCardLink'),
        ),
        migrations.AddField(
            model_name='scoreans',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
