# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160925_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True)),
                ('isopen', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scorecardlink',
            name='scorecard',
        ),
        migrations.AddField(
            model_name='batch',
            name='judgingopen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readout',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Batch'),
        ),
        migrations.AddField(
            model_name='scorecardlink',
            name='readout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ReadOut'),
        ),
    ]
