# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20160926_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ReadOut')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ScoreCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='scorecardlink',
            name='readout',
        ),
        migrations.AddField(
            model_name='scorecardlink',
            name='scorecard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ScoreCard'),
        ),
    ]
