# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160926_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecarduser',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
