# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_scorecarduser_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreqn',
            name='subqn',
            field=models.CharField(default='', max_length=200),
        ),
    ]
