# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_judges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judges',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
