# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160927_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreans',
            name='anschar',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
