# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160927_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreans',
            name='scorecarduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ScoreCardUser'),
        ),
    ]
