# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_scoreqn_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='scoreboardopen',
            field=models.BooleanField(default=False),
        ),
    ]
