# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQnsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('qn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.Qns')),
            ],
        ),
        migrations.CreateModel(
            name='CodeTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=50, unique=True)),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='codeqnslist',
            name='testid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetests.CodeTests'),
        ),
    ]
