# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 14:46
from __future__ import unicode_literals

import codetests.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQnsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodeTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=50, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('duration', models.IntegerField()),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('smalllimits', models.TextField()),
                ('largelimits', models.TextField()),
                ('inputexample', models.TextField()),
                ('outputexample', models.TextField()),
                ('utimesmall', models.IntegerField()),
                ('utimelarge', models.IntegerField()),
                ('smallscript', models.FileField(null=True, upload_to=codetests.models.smallscript_upload)),
                ('largescript', models.FileField(null=True, upload_to=codetests.models.largescript_upload)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='codeqnslist',
            name='qn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetests.Qns'),
        ),
        migrations.AddField(
            model_name='codeqnslist',
            name='testid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codetests.CodeTests'),
        ),
    ]
