# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qns',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
