# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetests',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
