# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetests', '0002_codetests_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetests',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
