# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-30 07:37
from __future__ import unicode_literals

import codetests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetests', '0003_auto_20160716_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='qns',
            name='directupload',
            field=models.FileField(null=True, upload_to=codetests.models.directupload_upload),
        ),
        migrations.AddField(
            model_name='qns',
            name='largescore',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='qns',
            name='need2questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qns',
            name='needdos2unix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qns',
            name='needtranslator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qns',
            name='numqnsuploaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qns',
            name='smallscore',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='qns',
            name='translatorscript',
            field=models.FileField(null=True, upload_to=codetests.models.translatorscript_upload),
        ),
        migrations.AddField(
            model_name='qns',
            name='usesuploadedqns',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='qns',
            name='largelimits',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='qns',
            name='utimelarge',
            field=models.IntegerField(null=True),
        ),
    ]
