# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetests', '0005_auto_20160730_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qns',
            old_name='numqnsuploaded',
            new_name='numqnsuploadedlarge',
        ),
        migrations.AddField(
            model_name='qns',
            name='numqnsuploadedsmall',
            field=models.IntegerField(default=0),
        ),
    ]
