# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetests', '0007_qns_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetests',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
